using System.Text.Json;
using Newtonsoft.Json;

namespace Tomoe.Utils {
    public class Dialog {
        [JsonProperty("embed")]
        public Classes.Embed Embed;

        [JsonProperty("format")]
        public Classes.Format Format;

        [JsonProperty("message")]
        public Classes.Message Message;
    }
}

//Generated by https://json2csharp.com/
namespace Tomoe.Utils.Classes {
    public class Ban {
        [JsonProperty("author")]
        public string Author;

        [JsonProperty("color")]
        public string Color;

        [JsonProperty("description")]
        public string Description;

        [JsonProperty("footer")]
        public string Footer;

        [JsonProperty("set_time")]
        public bool SetTime;

        [JsonProperty("thumbnail_url")]
        public string ThumbnailUrl;

        [JsonProperty("title")]
        public string Title;
    }

    public class Default {
        [JsonProperty("author")]
        public string Author;

        [JsonProperty("color")]
        public string Color;

        [JsonProperty("description")]
        public string Description;

        [JsonProperty("footer")]
        public string Footer;

        [JsonProperty("set_time")]
        public bool SetTime;

        [JsonProperty("thumbnail_url")]
        public string ThumbnailUrl;

        [JsonProperty("title")]
        public string Title;
    }

    public class Kick {
        [JsonProperty("author")]
        public string Author;

        [JsonProperty("color")]
        public string Color;

        [JsonProperty("description")]
        public string Description;

        [JsonProperty("footer")]
        public string Footer;

        [JsonProperty("set_time")]
        public bool SetTime;

        [JsonProperty("thumbnail_url")]
        public string ThumbnailUrl;

        [JsonProperty("title")]
        public string Title;
    }

    public class Mute {
        [JsonProperty("author")]
        public string Author;

        [JsonProperty("color")]
        public string Color;

        [JsonProperty("description")]
        public string Description;

        [JsonProperty("footer")]
        public string Footer;

        [JsonProperty("set_time")]
        public bool SetTime;

        [JsonProperty("thumbnail_url")]
        public string ThumbnailUrl;

        [JsonProperty("title")]
        public string Title;
    }

    public class NoMeme {
        [JsonProperty("author")]
        public string Author;

        [JsonProperty("color")]
        public string Color;

        [JsonProperty("description")]
        public string Description;

        [JsonProperty("footer")]
        public string Footer;

        [JsonProperty("set_time")]
        public bool SetTime;

        [JsonProperty("thumbnail_url")]
        public string ThumbnailUrl;

        [JsonProperty("title")]
        public string Title;
    }

    public class Strike {
        [JsonProperty("author")]
        public string Author;

        [JsonProperty("color")]
        public string Color;

        [JsonProperty("description")]
        public string Description;

        [JsonProperty("footer")]
        public string Footer;

        [JsonProperty("set_time")]
        public bool SetTime;

        [JsonProperty("thumbnail_url")]
        public string ThumbnailUrl;

        [JsonProperty("title")]
        public string Title;
    }

    public class TempBan {
        [JsonProperty("author")]
        public string Author;

        [JsonProperty("color")]
        public string Color;

        [JsonProperty("description")]
        public string Description;

        [JsonProperty("footer")]
        public string Footer;

        [JsonProperty("set_time")]
        public bool SetTime;

        [JsonProperty("thumbnail_url")]
        public string ThumbnailUrl;

        [JsonProperty("title")]
        public string Title;
    }

    public class TempMute {
        [JsonProperty("author")]
        public string Author;

        [JsonProperty("color")]
        public string Color;

        [JsonProperty("description")]
        public string Description;

        [JsonProperty("footer")]
        public string Footer;

        [JsonProperty("set_time")]
        public bool SetTime;

        [JsonProperty("thumbnail_url")]
        public string ThumbnailUrl;

        [JsonProperty("title")]
        public string Title;
    }

    public class TempNoMeme {
        [JsonProperty("author")]
        public string Author;

        [JsonProperty("color")]
        public string Color;

        [JsonProperty("description")]
        public string Description;

        [JsonProperty("footer")]
        public string Footer;

        [JsonProperty("set_time")]
        public bool SetTime;

        [JsonProperty("thumbnail_url")]
        public string ThumbnailUrl;

        [JsonProperty("title")]
        public string Title;
    }

    public class UnBan {
        [JsonProperty("author")]
        public string Author;

        [JsonProperty("color")]
        public string Color;

        [JsonProperty("description")]
        public string Description;

        [JsonProperty("footer")]
        public string Footer;

        [JsonProperty("set_time")]
        public bool SetTime;

        [JsonProperty("thumbnail_url")]
        public string ThumbnailUrl;

        [JsonProperty("title")]
        public string Title;
    }

    public class UnMute {
        [JsonProperty("author")]
        public string Author;

        [JsonProperty("color")]
        public string Color;

        [JsonProperty("description")]
        public string Description;

        [JsonProperty("footer")]
        public string Footer;

        [JsonProperty("set_time")]
        public bool SetTime;

        [JsonProperty("thumbnail_url")]
        public string ThumbnailUrl;

        [JsonProperty("title")]
        public string Title;
    }

    public class UnNoMeme {
        [JsonProperty("author")]
        public string Author;

        [JsonProperty("color")]
        public string Color;

        [JsonProperty("description")]
        public string Description;

        [JsonProperty("footer")]
        public string Footer;

        [JsonProperty("set_time")]
        public bool SetTime;

        [JsonProperty("thumbnail_url")]
        public string ThumbnailUrl;

        [JsonProperty("title")]
        public string Title;
    }

    public class Dm {
        [JsonProperty("ban")]
        public Ban Ban;

        [JsonProperty("default")]
        public Default Default;

        [JsonProperty("kick")]
        public Kick Kick;

        [JsonProperty("mute")]
        public Mute Mute;

        [JsonProperty("no_meme")]
        public NoMeme NoMeme;

        [JsonProperty("strike")]
        public Strike Strike;

        [JsonProperty("temp_ban")]
        public TempBan TempBan;

        [JsonProperty("temp_mute")]
        public TempMute TempMute;

        [JsonProperty("temp_no_meme")]
        public TempNoMeme TempNoMeme;

        [JsonProperty("un_ban")]
        public UnBan UnBan;

        [JsonProperty("un_mute")]
        public UnMute UnMute;

        [JsonProperty("un_no_meme")]
        public UnNoMeme UnNoMeme;
    }

    public class Embed {
        [JsonProperty("dm")]
        public Dm Dm;
    }

    public class Action {
        [JsonProperty("ban")]
        public bool Ban;

        [JsonProperty("default")]
        public bool Default;

        [JsonProperty("kick")]
        public bool Kick;

        [JsonProperty("mute")]
        public bool Mute;

        [JsonProperty("no_meme")]
        public bool NoMeme;

        [JsonProperty("strike")]
        public bool Strike;

        [JsonProperty("temp_ban")]
        public bool TempBan;

        [JsonProperty("temp_mute")]
        public bool TempMute;

        [JsonProperty("temp_no_meme")]
        public bool TempNoMeme;

        [JsonProperty("un_ban")]
        public bool UnBan;

        [JsonProperty("un_mute")]
        public bool UnMute;

        [JsonProperty("un_no_meme")]
        public bool UnNoMeme;
    }

    public class Dm2 {
        [JsonProperty("ban")]
        public bool Ban;

        [JsonProperty("default")]
        public bool Default;

        [JsonProperty("kick")]
        public bool Kick;

        [JsonProperty("mute")]
        public bool Mute;

        [JsonProperty("no_meme")]
        public bool NoMeme;

        [JsonProperty("strike")]
        public bool Strike;

        [JsonProperty("temp_ban")]
        public bool TempBan;

        [JsonProperty("temp_mute")]
        public bool TempMute;

        [JsonProperty("temp_no_meme")]
        public bool TempNoMeme;

        [JsonProperty("un_ban")]
        public bool UnBan;

        [JsonProperty("un_mute")]
        public bool UnMute;

        [JsonProperty("un_no_meme")]
        public bool UnNoMeme;
    }

    public class Format {
        [JsonProperty("action")]
        public Action Action;

        [JsonProperty("dm")]
        public Dm2 Dm;
    }

    public class Action2 {
        [JsonProperty("ban")]
        public string Ban;

        [JsonProperty("default")]
        public string Default;

        [JsonProperty("kick")]
        public string Kick;

        [JsonProperty("mute")]
        public string Mute;

        [JsonProperty("no_meme")]
        public string NoMeme;

        [JsonProperty("strike")]
        public string Strike;

        [JsonProperty("temp_ban")]
        public string TempBan;

        [JsonProperty("temp_mute")]
        public string TempMute;

        [JsonProperty("temp_no_meme")]
        public string TempNoMeme;

        [JsonProperty("un_ban")]
        public string UnBan;

        [JsonProperty("un_mute")]
        public string UnMute;

        [JsonProperty("un_no_meme")]
        public string UnNoMeme;
    }

    public class Dm3 {
        [JsonProperty("ban")]
        public string Ban;

        [JsonProperty("default")]
        public string Default;

        [JsonProperty("kick")]
        public string Kick;

        [JsonProperty("mute")]
        public string Mute;

        [JsonProperty("no_meme")]
        public string NoMeme;

        [JsonProperty("strike")]
        public string Strike;

        [JsonProperty("temp_ban")]
        public string TempBan;

        [JsonProperty("temp_mute")]
        public string TempMute;

        [JsonProperty("temp_no_meme")]
        public string TempNoMeme;

        [JsonProperty("un_ban")]
        public string UnBan;

        [JsonProperty("un_mute")]
        public string UnMute;

        [JsonProperty("un_no_meme")]
        public string UnNoMeme;
    }

    public class Errors {
        [JsonProperty("exit")]
        public string Exit;

        [JsonProperty("failed_hierarchy_error")]
        public string FailedHierarchyError;

        [JsonProperty("failed_in_dm")]
        public string FailedInDm;

        [JsonProperty("failed_self_bot")]
        public string FailedSelfBot;

        [JsonProperty("failed_to_dm")]
        public string FailedToDm;

        [JsonProperty("no_bot_perms")]
        public string NoBotPerms;

        [JsonProperty("no_everyone_role")]
        public string NoEveryoneRole;

        [JsonProperty("no_reason")]
        public string NoReason;

        [JsonProperty("no_user_perms")]
        public string NoUserPerms;

        [JsonProperty("non_existing_role")]
        public string NonExistingRole;

        [JsonProperty("not_in_guild")]
        public string NotInGuild;

        [JsonProperty("user_not_banned")]
        public string UserNotBanned;

        [JsonProperty("user_already_banned")]
        public string UserAlreadyBanned;
    }

    public class Events {
        [JsonProperty("message_updated")]
        public string MessageUpdated;

        [JsonProperty("message_deleted")]
        public string MessageDeleted;
    }

    public class Guild {
        [JsonProperty("already_setup")]
        public string AlreadySetup;

        [JsonProperty("failed_user_permissions")]
        public string FailedUserPermissions;

        [JsonProperty("success_setup")]
        public string SuccessSetup;
    }

    public class Mute2 {
        [JsonProperty("already_setup")]
        public string AlreadySetup;

        [JsonProperty("corrected_permissions")]
        public string CorrectedPermissions;

        [JsonProperty("exit")]
        public string Exit;

        [JsonProperty("failed_bot_permissions")]
        public string FailedBotPermissions;

        [JsonProperty("failed_same_role")]
        public string FailedSameRole;

        [JsonProperty("failed_user_permissions")]
        public string FailedUserPermissions;

        [JsonProperty("fix_permissions")]
        public string FixPermissions;

        [JsonProperty("missing_role")]
        public string MissingRole;

        [JsonProperty("not_setup")]
        public string NotSetup;

        [JsonProperty("success_setup")]
        public string SuccessSetup;
    }

    public class NoMeme2 {
        [JsonProperty("already_setup")]
        public string AlreadySetup;

        [JsonProperty("corrected_permissions")]
        public string CorrectedPermissions;

        [JsonProperty("exit")]
        public string Exit;

        [JsonProperty("failed_bot_permissions")]
        public string FailedBotPermissions;

        [JsonProperty("failed_same_role")]
        public string FailedSameRole;

        [JsonProperty("failed_user_permissions")]
        public string FailedUserPermissions;

        [JsonProperty("fix_permissions")]
        public string FixPermissions;

        [JsonProperty("missing_role")]
        public string MissingRole;

        [JsonProperty("not_setup")]
        public string NotSetup;

        [JsonProperty("success_setup")]
        public string SuccessSetup;
    }

    public class Setup {
        [JsonProperty("guild")]
        public Guild Guild;

        [JsonProperty("mute")]
        public Mute2 Mute;

        [JsonProperty("no_meme")]
        public NoMeme2 NoMeme;
    }

    public class Message {
        [JsonProperty("action")]
        public Action2 Action;

        [JsonProperty("dm")]
        public Dm3 Dm;

        [JsonProperty("errors")]
        public Errors Errors;

        [JsonProperty("events")]
        public Events Events;

        [JsonProperty("setup")]
        public Setup Setup;
    }

    public class Root {
        [JsonProperty("embed")]
        public Embed Embed;

        [JsonProperty("format")]
        public Format Format;

        [JsonProperty("message")]
        public Message Message;
    }
}