CREATE TABLE IF NOT EXISTS guild_cache(
	guild_id BIGINT NOT NULL,
	user_id BIGINT NOT NULL,
	role_ids TEXT,
	muted BOOLEAN NOT NULL DEFAULT FALSE,
	antimemed BOOLEAN NOT NULL DEFAULT FALSE,
	vc_banned BOOLEAN NOT NULL DEFAULT FALSE
);
