PRAGMA case_sensitive_like = true;
CREATE TABLE IF NOT EXISTS strikes(
	GUILD_ID BIGINT NOT NULL,
	VICTIM_ID BIGINT NOT NULL,
	ISSUER_ID BIGINT NOT NULL,
	REASON TEXT NOT NULL,
	JUMPLINK VARCHAR(100) NOT NULL,
	VICTIM_MESSAGED BOOLEAN NOT NULL,
	DROPPED BOOLEAN NOT NULL DEFAULT FALSE,
	STRIKE_COUNT TINYINT NOT NULL DEFAULT 0,
	CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
);
REINDEX strikes;
