using System;
using System.Collections.Generic;
using System.Linq;

namespace OoLunar.Tomoe.Database.Models
{
    /// <summary>
    /// Represents a role menu in the database. Used for handing out roles to guild members.
    /// </summary>
    public sealed class RoleMenuModel
    {
        /// <summary>
        /// The object id generated by the database.
        /// </summary>
        /// <value></value>
        public Guid Id { get; init; }

        /// <summary>
        /// The id of the guild that the role menu is in.
        /// </summary>
        public ulong GuildId { get; init; }

        /// <summary>
        /// The ids of the roles that the role menu is for.
        /// </summary>
        public List<ulong> RoleIds { get; init; }

        public RoleMenuModel() { }

        /// <summary>
        /// Creates a new <see cref="RoleMenuModel"/> from a <see cref="DiscordGuild"/> and multiple <see cref="DiscordRole"/>s.
        /// </summary>
        public RoleMenuModel(ulong guildId, Guid menuId, params ulong[] roleIds)
        {
            GuildId = guildId;
            Id = menuId;
            RoleIds = roleIds.ToList();
        }

        public static bool operator ==(RoleMenuModel? left, RoleMenuModel? right) => Equals(left, right);
        public static bool operator !=(RoleMenuModel? left, RoleMenuModel? right) => !Equals(left, right);
        public override bool Equals(object? obj) => obj is RoleMenuModel model && Id.Equals(model.Id) && GuildId == model.GuildId && EqualityComparer<List<ulong>>.Default.Equals(RoleIds, model.RoleIds);
        public override int GetHashCode() => HashCode.Combine(Id, GuildId, RoleIds);
    }
}
